force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Account_Retail_Store__c/Account_Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Account Retail Store</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Account Retail Store Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Retail_Store__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Retail Stores</relationshipLabel>
    <relationshipName>Account_Reatile_Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Retail_Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor-Approve</fullName>
            </value>
            <value>
                <fullName>Distributor-Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RetailerInitialApprovalSubControllerTest.cls
@isTest(seealldata=true)
private class RetailerInitialApprovalSubControllerTest {

    @isTest
    static void testSubmitForApproval_Success() {
       Account acc = [select id from Account limit 1];
        
       Account_Retail_Store__c rets = [SELECT Id,Name, Account__c,Status__c FROM Account_Retail_Store__c WHERE Status__c='Distributor-Reject' limit 1];
        // Create test data
       
 List<Contact> contactList = [SELECT Id, AccountId, Is_primary_Contact__c FROM Contact WHERE AccountId = :acc.Id AND Is_primary_Contact__c = true LIMIT 1];

        List<User> userList = [SELECT Id,Name, Username, Email, IsActive, ContactId FROM User WHERE ContactId = :contactList[0].Id AND IsActive = true LIMIT 1];

        // Call the method to be tested
        Test.startTest();
        String result = RetailerInitialApprovalSubController.submitForApproval(rets.Id, 'https://google.com');
        Test.stopTest();

    }

 
  
}