force-app/main/default/objects/Product2/fields/Bundle_Price__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Price__c</fullName>
    <label>Bundle Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Price_with_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Price_with_Quantity__c</fullName>
    <label>Bundle Price with Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Price_With_VAT__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Price_With_VAT__c</fullName>
    <label>Bundle Price With VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Price_with_VAT_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Price_with_VAT_Quantity__c</fullName>
    <label>Bundle Price with VAT &amp; Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Quantity__c</fullName>
    <label>Bundle Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Notes__c.field-meta.xml
<CustomField>
    <fullName>Unit_Notes__c</fullName>
    <label>Unit Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Updated_Price_from_Line_item__c.field-meta.xml
<CustomField>
    <fullName>Updated_Price_from_Line_item__c</fullName>
    <label>Updated Price from Line item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Brand_Change_Note__c.field-meta.xml
<CustomField>
    <fullName>Brand_Change_Note__c</fullName>
    <defaultValue>&quot;If a component in the requested brand is unavailable an equivalent component from another brand which meets the relevent standards will be used instead&quot;</defaultValue>
    <label>Brand Change Note</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price__c</fullName>
    <formula>Rep_Discount__c * Products_Price_with_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Grand_Total_price_with_VAT__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_price_with_VAT__c</fullName>
    <formula>Vat_Amount__c +   Products_Price_with_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total price with VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Grand_total_price_with_VAT_Discount__c.field-meta.xml
<CustomField>
    <fullName>Grand_total_price_with_VAT_Discount__c</fullName>
    <formula>Product_Price_With_Discount__c + Vat_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand total price with VAT &amp; Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Grand_Total_with_Qty_VAT_I_H__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_with_Qty_VAT_I_H__c</fullName>
    <label>Grand Total with Qty &amp; VAT - (I.H.)</label>
    <summarizedField>QuoteLineItem.Final_Bundle_Price_with_VAT_Quantity__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>60% Advance balance before delivery</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>30 Days Credit</fullName>
            </value>
            <value>
                <fullName>CASH</fullName>
            </value>
            <value>
                <fullName>60 Days Credit</fullName>
            </value>
            <value>
                <fullName>F.O.C.</fullName>
            </value>
            <value>
                <fullName>60% Advance. Balance 60 days Credit</fullName>
            </value>
            <value>
                <fullName>60% Advance. Balance 30 days Credit</fullName>
            </value>
            <value>
                <fullName>LC@Sight</fullName>
            </value>
            <value>
                <fullName>20% Payment to reserve and confirm the order</fullName>
            </value>
            <value>
                <fullName>LC@ 90 days credit</fullName>
            </value>
            <value>
                <fullName>TT</fullName>
            </value>
            <value>
                <fullName>0 days</fullName>
            </value>
            <value>
                <fullName>LC@ 45 Days Credit</fullName>
            </value>
            <value>
                <fullName>LC@ 30 Days Credit</fullName>
            </value>
            <value>
                <fullName>50% Advance, Balance 30 days Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Product_Price_With_Discount__c.field-meta.xml
<CustomField>
    <fullName>Product_Price_With_Discount__c</fullName>
    <formula>Products_Price_with_Quantity__c - Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Price With Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Products_Price_with_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Products_Price_with_Quantity__c</fullName>
    <label>Products Price with Quantity</label>
    <summarizedField>QuoteLineItem.Final_Bundle_Price_with_Quantity__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quote_vise_Notes__c.field-meta.xml
<CustomField>
    <fullName>Quote_vise_Notes__c</fullName>
    <label>Quote vise Notes</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rep_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Rep_Delivery__c</fullName>
    <label>Rep. Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ex-Stock Prior to Sale</fullName>
            </value>
            <value>
                <fullName>(Ex-Works)4-5 weeks from sale</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 4 working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 5 working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 7 working Days after drawings confirmation (Ex-works) 10 working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 1-2 weeks after drawings confirmation (Ex-works) 2-3 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 6-8 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 2-4 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 4-6 working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 4-6 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 8-12 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-Works) 2-3 weeks after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-Works) 2-3 Working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>14 Working Days after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 4-6 Months after drawings confirmation</fullName>
            </value>
            <value>
                <fullName>(Ex-works) 3-4 Months after drawings confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Rep_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rep_Discount__c</fullName>
    <label>Rep Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Rep_Validity__c.field-meta.xml
<CustomField>
    <fullName>Rep_Validity__c</fullName>
    <label>Rep. Validity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7 Days</fullName>
            </value>
            <value>
                <fullName>14 Days</fullName>
            </value>
            <value>
                <fullName>21 Days</fullName>
            </value>
            <value>
                <fullName>30 Days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VAT</fullName>
            </value>
            <value>
                <fullName>SVAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
            <value>
                <fullName>Include (Hidden)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Vat_Amount__c.field-meta.xml
<CustomField>
    <fullName>Vat_Amount__c</fullName>
    <formula>Products_Price_with_Quantity__c  * ( VAT_Percentage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vat Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Electrical_Labour_Amount__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Labour_Amount__c</fullName>
    <formula>Electrical_Labour__c *  Electrical_Labour_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Electrical Labour Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Engraving_Tags_With_Legend_Plates_Amount__c.field-meta.xml
<CustomField>
    <fullName>Engraving_Tags_With_Legend_Plates_Amount__c</fullName>
    <formula>Engraving_Tags_With_Legend_Plates__c *  Engraving_Tags_With_Legend_Plates_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Engraving Tags With Legend Plates Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Instalation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Instalation_Amount__c</fullName>
    <formula>Instalation_Charges__c *  Instalation_Charges_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instalation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Transport_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transport_Amount__c</fullName>
    <formula>Transport_Charges__c *  Transport_Charges_Hours__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transport Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>Final_Bundle_Price__c *  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/repeaterExtensionClass.cls
public class repeaterExtensionClass {

      public String MstrId{GET;SET;}
    public List<QuoteLineItem> QuoteLineItems { get;  set; }
    public List<cgcloud__Product_Part__c> ProductsWith { get; set; }
        public List<Product2> Prod { get; set; }
    public String baseURL{GET;SET;}
     public Quote QuoteObj{GET;SET;}
     public String accowner { get; set; }
    
public repeaterExtensionClass(ApexPages.StandardController Controller){ 
      baseURL = URL.getSalesforceBaseUrl().toExternalForm(); 
    MstrId = controller.getId();  
    
       QuoteObj =  [SELECT Id, opportunityId,Name,  QuoteNumber,Subtotal,Tax,Tax_Type__c,VAT__c, Discount,CreatedBy.name,Grand_Total_price_with_VAT__c,Rep_Discount__c,Discounted_Price__c,Product_Price_With_Discount__c,
                    Vat_Amount__c,Products_Price_with_Quantity__c,Grand_total_price_with_VAT_Discount__c,Grand_Total_with_Qty_VAT_I_H__c,Brand_Change_Note__c,Quote_vise_Notes__c,Payment_Terms__c,Rep_Delivery__c,Rep_Validity__c,
                   Accountid, account.name, account.createdbyID,Account.Owner.name,Account.Owner.Phone,contact.name,
                          (SELECT Id,Product2Id, Quantity, UnitPrice, Product2.Name,PricebookEntry.Product2.Name,
                            Discount,LineNumber,TotalPrice,Electrical_Labour_Amount__c, Engraving_Tags_With_Legend_Plates_Amount__c, Instalation_Amount__c, Transport_Amount__c, Subtotal FROM Quotelineitems) 
                               FROM Quote WHERE Id = : MstrId];
        
       QuoteLineItems =[SELECT Id,Product2Id, Quantity, UnitPrice, Product2.Name,PricebookEntry.Product2.Name,
                             Discount,LineNumber,TotalPrice, Subtotal, Electrical_Labour_Amount__c, Engraving_Tags_With_Legend_Plates_Amount__c, Instalation_Amount__c, Transport_Amount__c 
                             FROM Quotelineitem  WHERE QuoteId = :MstrId];     
    
    List<Id> productIds = new List<Id>();
        for (QuoteLineItem lineItem : QuoteLineItems) {
            productIds.add(lineItem.Product2Id);
        }

// ProductsWith=[SELECT Id, name, cgcloud__Quantity__c,cgcloud__Parent_Product__r.name from cgcloud__Product_Part__c where cgcloud__Parent_Product__c =:productIds ];
    
    Prod = [Select Id, Name,Bundle_Price__c,Updated_Price_from_Line_item__c,Bundle_Price_with_Quantity__c,Bundle_Price_With_VAT__c,Bundle_Price_with_VAT_Quantity__c,Bundle_Quantity__c,Unit_Notes__c,
                (Select Id, name,cgcloud__Quantity__c,cgcloud__Child_Product__r.Name,Part_Description__c From cgcloud__Product_Parts__r  ) from Product2 where Id=: productIds];
    
   
 //   system.debug('the producyts are== '+ProductsWith);
    
    System.debug('The Original products are == '+Prod);
    
}
  
    
}