force-app/main/default/objects/Account/fields/De_Boarding_Reason__c.field-meta.xml
<CustomField>
    <fullName>De_Boarding_Reason__c</fullName>
    <label>De-Boarding Reason</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deboarding_process_status__c.field-meta.xml
<CustomField>
    <fullName>Deboarding_process_status__c</fullName>
    <label>Deboarding process status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deboarding Initiated</fullName>
            </value>
            <value>
                <fullName>In Process - Working with Reconciliation &amp; Full and Final Settlement</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/orel_Deboard_Initiated__c.field-meta.xml
<CustomField>
    <fullName>orel_Deboard_Initiated__c</fullName>
    <label>orel Deboard Initiated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated by Distributor</fullName>
            </value>
            <value>
                <fullName>Initiated by Non-Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/OrelRequestTracking__c/OrelRequestTracking__c.object-meta.xml
<CustomObject>
    <description>All the Distributor requests will be tracked here.</description>
    <label>OrelRequestTracking</label>
    <nameField>
        <displayFormat>Req-{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrelRequestTracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrelRequestTracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Deboarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/Orel_Initiated_By__c.field-meta.xml
<CustomField>
    <fullName>Orel_Initiated_By__c</fullName>
    <label>Orel Initiated By</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/Orel_Reason__c.field-meta.xml
<CustomField>
    <fullName>Orel_Reason__c</fullName>
    <label>Orel Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/OrelStatus__c.field-meta.xml
<CustomField>
    <fullName>OrelStatus__c</fullName>
    <label>OrelStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deboard initiated</fullName>
            </value>
            <value>
                <fullName>Request Approved</fullName>
            </value>
            <value>
                <fullName>Request Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrelDeboardingController.cls
public without sharing class OrelDeboardingController {
    @AuraEnabled
    public static void createOrelRequestRecord(String userId, String reason) {
        String usacId = [SELECT Id, AccountId FROM User WHERE Id = :userId LIMIT 1].AccountId;
        system.debug('Print' +usacId);
        // Create a new OrelRequestTracking__c record
        OrelRequestTracking__c orelRequestRecord = new OrelRequestTracking__c(
            Account__c = usacId,
            Orel_Initiated_By__c = 'Initiated by Distributor',
            OrelStatus__c = 'Deboard initiated',
            Orel_Reason__c = reason
        );

        // Insert the new OrelRequestTracking__c record
        insert orelRequestRecord;
    }

    @AuraEnabled
    public static void updateAccountNonDist(String accountId, String reason) {
        system.debug('Entered apec class ' + accountId);
        Account acc = [SELECT Id, De_Boarding_Reason__c, Deboarding_process_status__c FROM Account WHERE Id = :accountId];
        system.debug('account list ' + acc);
        acc.De_Boarding_Reason__c = reason;
        acc.Deboarding_process_status__c = 'In Process - Working with Reconciliation & Full and Final Settlement';
        acc.orel_Deboard_Initiated__c ='Initiated by Non-Distributor';
        update acc;
    }
}