force-app/main/default/objects/OrelRequestTracking__c/OrelRequestTracking__c.object-meta.xml
<CustomObject>
    <description>All the Distributor requests will be tracked here.</description>
    <label>OrelRequestTracking</label>
    <nameField>
        <displayFormat>Req-{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrelRequestTracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrelRequestTracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Deboarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/Orel_Initiated_By__c.field-meta.xml
<CustomField>
    <fullName>Orel_Initiated_By__c</fullName>
    <label>Orel Initiated By</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/Orel_Reason__c.field-meta.xml
<CustomField>
    <fullName>Orel_Reason__c</fullName>
    <label>Orel Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrelRequestTracking__c/fields/OrelStatus__c.field-meta.xml
<CustomField>
    <fullName>OrelStatus__c</fullName>
    <label>OrelStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deboard initiated</fullName>
            </value>
            <value>
                <fullName>Request Approved</fullName>
            </value>
            <value>
                <fullName>Request Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrelRequestTrackingController.cls
// OrelRequestTrackingController.cls
public with sharing class OrelRequestTrackingController {

    @AuraEnabled(cacheable=true)
    public static List<OrelRequestTracking__c> getOrelRequestsByUser() {
        // Get the current user's Id
        Id userId = UserInfo.getUserId();

        // Query the User's related Account Id
        Id userAccountId = [SELECT AccountId FROM User WHERE Id = :userId].AccountId;

        // Perform SOQL query to fetch OrelRequestTracking__c records based on the user's Account
        return [SELECT Id, Name, Account__c, Account__r.Name, Orel_Reason__c, OrelStatus__c, Orel_Initiated_By__c
                FROM OrelRequestTracking__c
                WHERE Account__c = :userAccountId];
    }
}