force-app/main/default/objects/Stock_Audit__c/Stock_Audit__c.object-meta.xml
<CustomObject>
    <label>Stock Audit</label>
    <nameField>
        <displayFormat>SA-{00}</displayFormat>
        <label>Stock Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Audits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Audit__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stock Audits</relationshipLabel>
    <relationshipName>Stock_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Audit__c/fields/Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Type__c</fullName>
    <label>Inventory type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Inventory</fullName>
            </value>
            <value>
                <fullName>Distributor Inventory</fullName>
            </value>
            <value>
                <fullName>Van Inventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/Stock_Audit_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Audit Line Item</label>
    <nameField>
        <displayFormat>Item-{00}</displayFormat>
        <label>Stock Audit Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Audit Line Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Actual_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Orl_Actual_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Expected_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Orl_Expected_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expected Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Orl_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>cgcloud__Inventory__c</referenceTo>
    <relationshipLabel>Stock Audit Line Items</relationshipLabel>
    <relationshipName>Stock_Audit_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>Orl_Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Orl_Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Audit_Line_Item__c/fields/Orl_Stock_Audit__c.field-meta.xml
<CustomField>
    <fullName>Orl_Stock_Audit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Audit</label>
    <referenceTo>Stock_Audit__c</referenceTo>
    <relationshipLabel>Stock Audit Line Items</relationshipLabel>
    <relationshipName>Stock_Audit_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockAuditController.cls
public class StockAuditController {
    public Stock_Audit__c Stocks {get;set;}
    private final Stock_Audit__c originalStocks;
    public list<Stock_Audit_Line_Item__c> StockLineItems {get;set;}

    public StockAuditController(ApexPages.StandardController stdController) {

        this.originalStocks = (Stock_Audit__c)stdController.getRecord();
        System.debug('OriginalStocks=> '+this.originalStocks);

        Stocks = [Select Id,Name,Audit_Date__c,(Select Id,Name,Orl_Actual_Quantity__c from Stock_Audit_Line_Items__r),Customer__r.Name,Inventory_Type__c from Stock_Audit__c where Id=:originalStocks.Id];
        
        StockLineItems = [Select Id,Name,Orl_Actual_Quantity__c,Orl_Expected_Quantity__c,Orl_Product_Name__c,Orl_Inventory_Type__c,Orl_Inventory__c
                           from Stock_Audit_Line_Item__c where Orl_Stock_Audit__c =:Stocks.Id];

        

    }
}