force-app/main/default/objects/Orl_invoice__c/Orl_invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Orl_invoice__c/fields/Advanced_Order__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advanced Order</label>
    <referenceTo>cgcloud__Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Advanced_Order__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advanced Order</label>
    <referenceTo>cgcloud__Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Orl_invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit/Debit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Type_of_payment__c</fullName>
    <label>Type of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Full Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrelPaymentVFClass.cls
public class OrelPaymentVFClass {
    
    public String receiptNumber { get; private set; }
    public String customer { get; private set; }
    public String orderNumber { get; private set; }
    public String invoiceNumber { get; private set; }
    public String typeOfPayment { get; private set; }
    public String modeOfPayment { get; private set; }
    public Decimal amountPaid { get; private set; }
    public String paymentReceivedBy { get; private set; }
    public String name { get; private set; }

    public OrelPaymentVFClass(ApexPages.StandardController controller) {
        String paymentId = ApexPages.currentPage().getParameters().get('id');
        system.debug('this is paymentID'+paymentId);
        Payment__c payment = [SELECT Id, Name, Type_of_payment__c, Invoice__r.Name, Advanced_Order__r.cgcloud__Order_Account__r.Name, Advanced_Order__r.Name, Amount_Paid__c, Mode_of_Payment__c FROM Payment__c WHERE Id = :paymentId LIMIT 1];
        
        receiptNumber = payment.Name;
        customer = payment.Advanced_Order__r.cgcloud__Order_Account__r.Name;
        orderNumber = payment.Advanced_Order__r.Name;
        invoiceNumber = payment.Invoice__r.Name;
        typeOfPayment = payment.Type_of_payment__c;
        modeOfPayment = payment.Mode_of_Payment__c;
        amountPaid = payment.Amount_Paid__c;
        paymentReceivedBy = '...'; // You can assign value accordingly
        name = '...'; // You can assign value accordingly
    }
}