force-app/main/default/objects/Opportunity/fields/PFP_Percent__c.field-meta.xml
<CustomField>
    <fullName>PFP_Percent__c</fullName>
    <label>PFP %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TPC_Percent__c.field-meta.xml
<CustomField>
    <fullName>TPC_Percent__c</fullName>
    <label>TPC %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
                <default>true</default>
                <label>Include</label>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
            <value>
                <fullName>Include (Hidden)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAT_Percentage__c.field-meta.xml
<CustomField>
    <fullName>VAT_Percentage__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>VAT Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/AFP_Percent__c.field-meta.xml
<CustomField>
    <fullName>AFP_Percent__c</fullName>
    <label>AFP %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Electrical_Labour__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Labour__c</fullName>
    <defaultValue>731.21</defaultValue>
    <label>Electrical Labour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Electrical_Labour_Hours__c.field-meta.xml
<CustomField>
    <fullName>Electrical_Labour_Hours__c</fullName>
    <label>Electrical Labour Hours</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Engraving_Tags_With_Legend_Plates__c.field-meta.xml
<CustomField>
    <fullName>Engraving_Tags_With_Legend_Plates__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Engraving Tags With Legend Plates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Engraving_Tags_With_Legend_Plates_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engraving_Tags_With_Legend_Plates_Hours__c</fullName>
    <label>Engraving Tags With Legend Plates Hours</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Final_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Price__c</fullName>
    <label>Final Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Govt_Entity__c.field-meta.xml
<CustomField>
    <fullName>Govt_Entity__c</fullName>
    <defaultValue>85</defaultValue>
    <label>Govt Entity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Instalation_Charges__c.field-meta.xml
<CustomField>
    <fullName>Instalation_Charges__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Instalation Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PFP_Percent__c.field-meta.xml
<CustomField>
    <fullName>PFP_Percent__c</fullName>
    <label>PFP %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TPC_Percent__c.field-meta.xml
<CustomField>
    <fullName>TPC_Percent__c</fullName>
    <label>TPC %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Transport_Charges__c.field-meta.xml
<CustomField>
    <fullName>Transport_Charges__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Transport Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/cgcloud__Product_Level__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Product_Level__c</fullName>
    <description>Describes the Product Level.</description>
    <label>Product Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>SubCategory</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Flavor</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
                <default>true</default>
                <label>Product</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/cgcloud__Product_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Product_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to product template.</description>
    <label>Product Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Product_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Product_Template__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Product_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Bundle__c/Product_Bundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
            <value>
                <fullName>Include (Hidden)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT_Percentage__c.field-meta.xml
<CustomField>
    <fullName>VAT_Percentage__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>VAT Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/createRepeaterQuoteTest.cls
@isTest
private class createRepeaterQuoteTest {
    @isTest
    static void testCreateRepeaterQuote() {
        
        
          cgcloud__Product_Template__c templates = new cgcloud__Product_Template__c(
        	Name = 'Test Template',
            cgcloud__Sales_Org__c = '0001',
            cgcloud__Active__c = true,
            cgcloud__Description_Language_1__c = 'test Description'
        	);
        Insert templates;
        
  
   //     Pricebook2 standardPricebook;

//    standardPricebook = [SELECT Id, Name FROM Pricebook2 WHERE isStandard = true];

   Id standardPricebook = Test.getStandardPricebookId();
        
           
        product2 prod = new product2(
            name = 'test product',
            cgcloud__Product_Template__c = templates.Id,
            cgcloud__Product_Level__c = 'Product',
            cgcloud__Description_1_Language_1__c = 'tst Desc',
            cgcloud__Consumer_Goods_Product_Code__c = 'Test code',
            Product_Bundle__c = false
        );
        Insert prod;

        // Create PricebookEntry linking the Product to the Standard Pricebook
        PricebookEntry testPricebookEntry = new PricebookEntry(
            Pricebook2Id = standardPricebook,
            Product2Id = prod.Id,
            UnitPrice = 1000.00,
            IsActive = true
        );
        insert testPricebookEntry;

        // Create Custom Pricebook
        Pricebook2 customPricebook = new Pricebook2(
            Name = 'SriLankan Currency PB',
            IsActive = true
        );
        insert customPricebook;

        // Create PricebookEntry linking the Product to the Custom Pricebook
        PricebookEntry customPricebookEntry = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = prod.Id,
            UnitPrice = 1200.00,
            IsActive = true
        );
        insert customPricebookEntry;

        
        // Create test Account
        Account testAccount = new Account(
            Name = 'Test Account'
            // Add other required fields as needed
        );
        insert testAccount;
        
        // Create test Contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testAccount.Id,
            Email = 'test@example.com',
            Phone = '1234567890'
            // Add other required fields as needed
        );
        insert testContact;
        
        // Create test Opportunity
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            CloseDate = Date.today(),
            Amount = 1000,
            StageName ='Qualification',
            VAT_Percentage__c = 10,
            VAT__c = 'Include'
            // Add other required fields as needed
        );
        insert testOpportunity;
        
        // Create test OpportunityLineItem
        OpportunityLineItem testOLI = new OpportunityLineItem(
            OpportunityId = testOpportunity.Id,
            Product2Id = prod.Id,
             PricebookEntryId = customPricebookEntry.Id,
            Quantity = 1,
            UnitPrice = 1000,
            Final_Price__c = 900,
            AFP_Percent__c = 5,
            PFP_Percent__c = 10,
            TPC_Percent__c = 15,
            Electrical_Labour_Hours__c = 20,
            Transport_Charges__c = 30,
            Instalation_Charges__c = 40,
            Electrical_Labour__c = 50,
            Engraving_Tags_With_Legend_Plates_Hours__c = 80,
            Engraving_Tags_With_Legend_Plates__c = 90,
            Govt_Entity__c = 22
            // Add other required fields as needed
        );
        insert testOLI;
        
        Test.startTest();
        // Call the method being tested
        List<Id> createdQuoteIds = createRepeaterQuote.createStandardQuote(new List<Id>{testOpportunity.Id});
        Test.stopTest();
        
        // Verify that a Quote was created
        System.assertNotEquals(0, createdQuoteIds.size(), 'No Quote was created');
        
        // Add more assertions as needed to validate the behavior of the method
    }
}