force-app/main/default/objects/Opportunity/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
                <default>true</default>
                <label>Include</label>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
            <value>
                <fullName>Include (Hidden)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAT_Percentage__c.field-meta.xml
<CustomField>
    <fullName>VAT_Percentage__c</fullName>
    <defaultValue>0.18</defaultValue>
    <label>VAT Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Runner.recordType-meta.xml
<RecordType>
    <fullName>Runner</fullName>
    <active>true</active>
    <businessProcess>Runner Flow</businessProcess>
    <label>Runner</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Final_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Price__c</fullName>
    <label>Final Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/cgcloud__Product_Level__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Product_Level__c</fullName>
    <description>Describes the Product Level.</description>
    <label>Product Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>SubCategory</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Flavor</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
                <default>true</default>
                <label>Product</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/cgcloud__Product_Template__c.field-meta.xml
<CustomField>
    <fullName>cgcloud__Product_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to product template.</description>
    <label>Product Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>cgcloud__Product_Template__c.cgcloud__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>cgcloud__Product_Template__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Product_Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Bundle__c/Product_Bundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/createRunnerQuoteTest.cls
@isTest
private class createRunnerQuoteTest {
    @isTest
    static void testCreateRunnerQuote() {
        
        
          cgcloud__Product_Template__c templates = new cgcloud__Product_Template__c(
        	Name = 'Test Template',
            cgcloud__Sales_Org__c = '0001',
            cgcloud__Active__c = true,
            cgcloud__Description_Language_1__c = 'test Description'
        	);
        Insert templates;
        
  
   //     Pricebook2 standardPricebook;

//    standardPricebook = [SELECT Id, Name FROM Pricebook2 WHERE isStandard = true];

   Id standardPricebook = Test.getStandardPricebookId();
        
           
        product2 prod = new product2(
            name = 'test product',
            cgcloud__Product_Template__c = templates.Id,
            cgcloud__Product_Level__c = 'Product',
            cgcloud__Description_1_Language_1__c = 'tst Desc',
            cgcloud__Consumer_Goods_Product_Code__c = 'Test code',
            Product_Bundle__c = false
        );
        Insert prod;

        // Create PricebookEntry linking the Product to the Standard Pricebook
        PricebookEntry testPricebookEntry = new PricebookEntry(
            Pricebook2Id = standardPricebook,
            Product2Id = prod.Id,
            UnitPrice = 1000.00,
            IsActive = true
        );
        insert testPricebookEntry;

        // Create Custom Pricebook
        Pricebook2 customPricebook = new Pricebook2(
            Name = 'Runner Pricebook',
            IsActive = true
        );
        insert customPricebook;

        // Create PricebookEntry linking the Product to the Custom Pricebook
        PricebookEntry customPricebookEntry = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = prod.Id,
            UnitPrice = 1200.00,
            IsActive = true
        );
        insert customPricebookEntry;

        // Create test Account
        Account testAccount = new Account(
            Name = 'Test Account'
        );
        insert testAccount;

        // Create test Contact
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = testAccount.Id,
            Email = 'test@example.com',
            Phone = '1234567890'
        );
        insert testContact;

        // Create test Opportunity
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            CloseDate = Date.today(),
            Amount = 1200,
            VAT_Percentage__c = 10,
            VAT__c = 'Include',
            StageName = 'Qualification'
        );
        insert testOpportunity;

        // Create test OpportunityLineItem
        OpportunityLineItem testOLI = new OpportunityLineItem(
            OpportunityId = testOpportunity.Id,
            Product2Id = prod.Id,
            PricebookEntryId = customPricebookEntry.Id,
            Quantity = 1,
            UnitPrice = 1200,
            Final_Price__c = 900
        );
        insert testOLI;

        Test.startTest();
        // Call the method being tested
        List<Id> createdQuoteIds = createRunnerQuote.createRunnerQuote(new List<Id>{testOpportunity.Id});
        Test.stopTest();
        
    }
}